### ISSUE TITLE
Remove indirect plugins from dependencies.md & remove enforcer plugin

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#480]
We added the enforcer plugin to fix https://github.com/exasol/project-keeper/issues/436 / https://github.com/exasol/project-keeper/issues/442 / https://github.com/exasol/project-keeper/issues/444

This restrictions Maven to a certain version range which causes problems with different toolchains on different machines.

To avoid generating inconsistent `dependencies.md` file we decided to remove plugins that are not directly referenced by `pom.xml` and the generated parent pom. This ensures that plugins that are referenced by Maven indirectly are omitted from `dependencies.md`.

```[tasklist]
### Tasks
- [x] Update design: document decision why indirect plugins are omitted in dependencies.md
- [x] Remove indirect plugins from dependencies.md
- [x] Remove enforcer plugin from generated parent pom
```
