### ISSUE TITLE
Enable toolchains for Maven projects

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#508]
In order to fix https://github.com/exasol/error-code-crawler-maven-plugin/issues/95 in https://github.com/exasol/error-code-crawler-maven-plugin we need to upgrade the build to Java 17 as a dependency with vulnerabilities is not available for Java 11 any more.

This means all our Maven builds using error-code-crawler-maven-plugin will need to run with Java 17.

But compiling and testing must still be done with Java 11 to ensure compatibility. We can use [Maven toolchains](https://maven.apache.org/guides/mini/guide-using-toolchains.html) to configure a separate JVM for compiling and testing.

This will allow us to use Java 17 based maven plugins in all our projects.

```[tasklist]
### Tasks
- [x] Add instructions for developers to configure toolchain on their local machines
- [x] Verify that toolchain is configured on GitHub action runners
- [x] Add requirements and design
- [x] Allow configuring Java version for each Maven module in PK configuration
```

Content of `~/.m2/toolchains.xml` on github actions:
```
<?xml version="1.0"?>
<toolchains xmlns="http://maven.apache.org/TOOLCHAINS/1.1.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/TOOLCHAINS/1.1.0 https://maven.apache.org/xsd/toolchains-1.1.0.xsd">
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>17</version>
      <vendor>temurin</vendor>
      <id>temurin_17</id>
    </provides>
    <configuration>
      <jdkHome>/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.9-9/x64</jdkHome>
    </configuration>
  </toolchain>
  <toolchain>
    <type>jdk</type>
    <provides>
      <version>11</version>
      <vendor>temurin</vendor>
      <id>temurin_11</id>
    </provides>
    <configuration>
      <jdkHome>/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.21-9/x64</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
```
