### ISSUE TITLE
Automatic release process

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#516]
# Goal
The current release process using release-droid still requires manual steps that we want to automate.

# Implementation

## Release workflow `release.yml`

For Java projects (i.e. that have a `pom.xml` in the root project folder) generate a new `release.yml` GH workflow

1. Run pre-release checks using PK `verify-release` mode (see below)
2. Run `mvn verify` (same as `release_droid_prepare_original_checksum.yml`, using default Exasol DB version, no matrix build)
3. Run `mvn -Dgpg.skip=false deploy` (same as `release_droid_release_on_maven_central.yml`)
4. Create GitHub release
5. Create release
6. Use code name as title and the rest of the changelog file as body
7. Calculate sha256sum for release files (maybe add all checksums to a single sha256-checksums.txt file)
8. Attach files and sha256-checksums.txt to the GitHub release

## PK `verify-release` mode

This additional PK mode runs the normal PK `verify` plus additional pre-release checks like [release-droid](https://github.com/exasol/release-droid) (see [RD user guide](https://github.com/exasol/release-droid/blob/main/doc/user_guide/user_guide.md)):
* Check that release date in changelog is the current date
* Check that all issues referenced in the changelog are closed
* Check version number
    * Don't skip a version
    * Don't release the same version twice or
    * Don't release a version lower than the latest release.
    * Increment version number correctly, i.e. increment one of patch/minor/major version

# Out of scope
* Running the release build for multiple platforms
* Attaching release artifacts for multiple platforms
* Customize build artifacts in `release.yml` and `ci-build.yml` wokflows: https://github.com/exasol/project-keeper/issues/517
* Customize build steps in `release.yml` and `ci-build.yml`: https://github.com/exasol/project-keeper/issues/519

```[tasklist]
### Tasks
- [x] Add design & requirements
- [ ] https://github.com/exasol/project-keeper/pull/539
- [x] Document `verify-release` mode
- [ ] https://github.com/exasol/project-keeper/pull/538
- [ ] https://github.com/exasol/project-keeper/pull/541
```

**Comment by kaklakariada** [comment]
Working time for @kaklakariada 2024-03: 35:30h ~8pd
