### ISSUE TITLE
Customize build artifacts in `release.yml` and `ci-build.yml` wokflows

### ISSUE THREAD

**Issue by kaklakariada** [exasol/project-keeper#517]
# Goal
Currently many projects that need to customize the generated workflows need to exclude them from PK, causing additional maintenance effort for manually updating the workflows when upgrading PK.

# Implementation
## Configuration
This allows adapting the files attached to a new release. The following options for customizing must be supported:
* For sources with module `jar_artifact`: read the artifact name from `pom.xml`:  `maven-assembly-plugin` > `configuration` > `finalName`
  * This requires support for placeholders using properties like `document-files-virtual-schema-dist-${vs-common-document-files.version}-s3-${project.version}`
* For each of the `sources` in `.project-keeper.yml` allow specifying a list of release artifacts paths (evaluated relatively to the source path)
  * Potentially we need to allow placeholders like `${project.version}` in the file name
* PK automatically adds `target/error_code_report.json`
  * We expect that the user has configured `error-code-crawler:aggregate` in the root `pom.xml`.

## Using custom build artifacts
The custom release artifacts are used in the following places:
* `release.yml`: For each of the release artifact:
  * Fail build if the artifact is not available
  * Calculate checksums
  * Attach file and it's checksum to the release
* `ci-build.yml`
  * Fail build if the artifact is not available
  * Attach file to the workflow run

# Open Questions
* Generate one checksum file per release artifact or generate one file with checksums of all artifacts?

# Out of scope
* Specifying release artifacts for multiple platforms
* Uploading test results like the `classes.lst` for the S3 VS with `if: always()` (see [ci-build.yml](https://github.com/exasol/s3-document-files-virtual-schema/blob/main/.github/workflows/ci-build.yml#L70))
  * This must be done via a custom post-build step, see https://github.com/exasol/project-keeper/issues/519
* Aggregate `error_code_report.json` for multiple Maven modules. This is done by `error-code-crawler:aggregate`.
* Verifying that  `error-code-crawler:aggregate` is used in the root Maven module. This is a separate issue.

```[tasklist]
### Tasks
- [x] Add design & requirements
- [ ] Add configuration for custom build artifacts
- [ ] Document of custom build artifacts
- [ ] Generate workflows based on custom artifacts
```
